#!/bin/bash
set -e

# --- CONFIGURATION ---
TAP_REPO_DIR="/Users/yashmakan/AxiomCore/homebrew-tap"
CLI_REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RELEASE_DIR="$CLI_REPO_DIR/release"

# 1. Get Version from Argument
VERSION=$1
if [ -z "$VERSION" ]; then
    echo "❌ Error: No version provided."
    echo "Usage: ./publish.sh v0.0.8"
    exit 1
fi

# Strip 'v' for the version field in the Ruby formula
PLAIN_VERSION="${VERSION#v}"

# 2. Check for required files
ACORE_TAR="$RELEASE_DIR/acore-macos-arm64.tar.gz"
AXIOM_TAR="$RELEASE_DIR/axiom-macos-arm64.tar.gz"

if [[ ! -f "$ACORE_TAR" || ! -f "$AXIOM_TAR" ]]; then
    echo "❌ Error: Tarballs not found in $RELEASE_DIR"
    echo "Please run ./build.sh and ./scripts/create_release.sh first."
    exit 1
fi

# 3. Calculate SHAs
echo "🔍 Calculating checksums..."
ACORE_SHA=$(shasum -a 256 "$ACORE_TAR" | awk '{print $1}')
AXIOM_SHA=$(shasum -a 256 "$AXIOM_TAR" | awk '{print $1}')

echo "   Acore SHA: $ACORE_SHA"
echo "   Axiom SHA: $AXIOM_SHA"

# 4. Git Tag and Push (CLI Repo)
echo "🏷️  Tagging CLI repository with $VERSION..."
git add .
git commit -m "Release $VERSION" || echo "Nothing to commit"
git tag -a "$VERSION" -m "Release $VERSION"
git push origin main
git push origin "$VERSION"

# 5. Create GitHub Release
echo "🚀 Creating GitHub Release and uploading assets..."
gh release create "$VERSION" \
    "$ACORE_TAR" \
    "$AXIOM_TAR" \
    --title "$VERSION" \
    --notes "Release generated by automation script."

# 6. Update Homebrew Tap
echo "🍺 Updating Homebrew Tap at $TAP_REPO_DIR..."

update_formula() {
    local FORMULA_FILE="$1"
    local NAME="$2"
    local NEW_SHA="$3"

    # Update URL (handles the version in the URL path)
    sed -i '' "s|releases/download/.*/${NAME}-macos-arm64.tar.gz|releases/download/${VERSION}/${NAME}-macos-arm64.tar.gz|g" "$FORMULA_FILE"
    
    # Update SHA256
    sed -i '' "s|sha256 \".*\"|sha256 \"${NEW_SHA}\"|g" "$FORMULA_FILE"
    
    # Update Version
    sed -i '' "s|version \".*\"|version \"${PLAIN_VERSION}\"|g" "$FORMULA_FILE"
}

update_formula "$TAP_REPO_DIR/Formula/acore.rb" "acore" "$ACORE_SHA"
update_formula "$TAP_REPO_DIR/Formula/axiom.rb" "axiom" "$AXIOM_SHA"

# 7. Push Homebrew Tap Changes
echo "📤 Pushing changes to homebrew-tap..."
cd "$TAP_REPO_DIR"
git add .
git commit -m "Updating to $VERSION"
git push origin main

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Successfully published $VERSION"
echo "   1. CLI Repo Tagged & Pushed"
echo "   2. GitHub Release Created with Assets"
echo "   3. Homebrew Formulae Updated & Pushed"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Try: brew update && brew upgrade axiom"