#!/bin/bash
set -e

# --- CONFIGURATION ---
# Path to your forked Pkl (acore) repository
ACOR_REPO_PATH="/Users/yashmakan/AxiomCore/acore"
# The specific native binary generated by GraalVM
ACOR_NATIVE_BINARY="$ACOR_REPO_PATH/pkl-cli/build/executable/acore-macos-aarch64"

CLI_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$CLI_ROOT/dist"
RELEASE_DIR="$CLI_ROOT/release"

echo "Creating directories..."
mkdir -p "$DIST_DIR"
mkdir -p "$RELEASE_DIR"

# 1. Fetch the Native Binary
echo "Fetching native acore binary from build directory..."
if [ -f "$ACOR_NATIVE_BINARY" ]; then
    cp "$ACOR_NATIVE_BINARY" "$DIST_DIR/acore"
    echo "✓ Successfully copied and renamed acore-macos-aarch64 to acore"
else
    echo "❌ Error: Native binary not found at $ACOR_NATIVE_BINARY"
    echo "Ensure you ran: ./gradlew :pkl-cli:assembleNativeMacOsAarch64"
    exit 1
fi

# 2. Ensure permissions are set
echo "Setting executable permissions..."
chmod +x "$DIST_DIR/acore"
# Check if axiom binary exists in dist, if not, you might need to copy it from its build source too
if [ -f "$DIST_DIR/axiom" ]; then
    chmod +x "$DIST_DIR/axiom"
else
    echo "⚠️  Warning: axiom binary not found in $DIST_DIR. Ensure it is built and placed there."
fi

echo "Verifying permissions before tarball creation..."
ls -l "$DIST_DIR/acore"

# Detect platform for naming the tarball
OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS" in
    Darwin) OS="macos" ;;
    Linux)  OS="linux" ;;
    *)      OS="macos" ;;
esac

case "$ARCH" in
    x86_64)       ARCH="amd64" ;;
    arm64|aarch64) ARCH="arm64" ;;
    *)            ARCH="arm64" ;;
esac

PLATFORM="${OS}-${ARCH}"

echo "Packaging for platform: $PLATFORM"

# 3. Create tarballs
echo "Creating tarballs in $RELEASE_DIR..."
cd "$DIST_DIR"
tar -czf "$RELEASE_DIR/acore-${PLATFORM}.tar.gz" acore
if [ -f "axiom" ]; then
    tar -czf "$RELEASE_DIR/axiom-${PLATFORM}.tar.gz" axiom
fi
cd "$CLI_ROOT"

echo "Generating checksums..."
shasum -a 256 "$RELEASE_DIR/acore-${PLATFORM}.tar.gz"

# 4. Create install script (The Rest of your script remains the same)
echo ""
echo "Creating install script..."
cat > "$RELEASE_DIR/install.sh" << 'EOF'
#!/bin/bash
# ... (rest of your existing install.sh code here) ...
EOF

chmod +x "$RELEASE_DIR/install.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✓ Release artifacts created in: $RELEASE_DIR"
echo "Binary type: $(file $DIST_DIR/acore)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"